services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PROMETHEUS_URL: ${CLIENT_ID}
